name: test

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install
        run: |
          pip install pytest-tap
          pip install -e .[all]
      - name: style
        run: |
          flake8 .
      - name: unittest
        run: |
          pytest
